export const selectManufacturerImage = (manufacturer: string) => {
  switch (manufacturer) {
    case '현대':
      return require('../assets/images/Manufacturer/hyundai.png')
    case '기아':
      return require('../assets/images/Manufacturer/kia.png')
    case '쉐보레':
      return require('../assets/images/Manufacturer/chevrolet.png')
    case '르노':
      return require('../assets/images/Manufacturer/renault.png')
    case '쌍용':
      return require('../assets/images/Manufacturer/ssangyong.png')
    case '제네시스':
      return require('../assets/images/Manufacturer/genesis.png')
    case '알파 로메오':
      return require('../assets/images/Manufacturer/alfaromeo.png')
    case '아우디':
      return require('../assets/images/Manufacturer/audi.png')
    case '벤츠':
      return require('../assets/images/Manufacturer/benz.png')
    case 'BMW':
      return require('../assets/images/Manufacturer/bmw.png')
    case '캐딜락':
      return require('../assets/images/Manufacturer/cadillac.png')
    case '크라이슬러':
      return require('../assets/images/Manufacturer/chrysler.png')
    case '시트로엥':
      return require('../assets/images/Manufacturer/citroen.png')
    case '닷지':
      return require('../assets/images/Manufacturer/dodge.png')
    case '페라리':
      return require('../assets/images/Manufacturer/ferrari.png')
    case '피아트':
      return require('../assets/images/Manufacturer/fiat.png')
    case '포드':
      return require('../assets/images/Manufacturer/ford.png')
    case '혼다':
      return require('../assets/images/Manufacturer/honda.png')
    case '험머':
      return require('../assets/images/Manufacturer/hummer.png')
    case '인피니티':
      return require('../assets/images/Manufacturer/infiniti.png')
    case '재규어':
      return require('../assets/images/Manufacturer/jaguar.png')
    case '지프':
      return require('../assets/images/Manufacturer/jeep.png')
    case '랜드로버':
      return require('../assets/images/Manufacturer/landrover.png')
    case '렉서스':
      return require('../assets/images/Manufacturer/lexus.png')
    case '링컨':
      return require('../assets/images/Manufacturer/lincoln.png')
    case '마세라티':
      return require('../assets/images/Manufacturer/maserati.png')
    case '마쯔다':
      return require('../assets/images/Manufacturer/mazda.png')
    case '미니':
      return require('../assets/images/Manufacturer/mini.png')
    case '미쯔비시':
      return require('../assets/images/Manufacturer/mitsubishi.png')
    case '닛산':
      return require('../assets/images/Manufacturer/nissan.png')
    case '푸조':
      return require('../assets/images/Manufacturer/peugeot.png')
    case '포르쉐':
      return require('../assets/images/Manufacturer/porsche.png')
    case '스바루':
      return require('../assets/images/Manufacturer/subaru.png')
    case '스즈키':
      return require('../assets/images/Manufacturer/suzuki.png')
    case '테슬라':
      return require('../assets/images/Manufacturer/tesla.png')
    case '도요타':
      return require('../assets/images/Manufacturer/toyota.png')
    case '폭스바겐':
      return require('../assets/images/Manufacturer/volkswagen.png')
    case '볼보':
      return require('../assets/images/Manufacturer/volvo.png')
  }
}
